// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjX5xCa8Wl5yUkMu1x4rppi2a8Q7CsXso',
    appId: '1:257411804002:android:877b1d8867d1d547c39a3b',
    messagingSenderId: '257411804002',
    projectId: 'g-austro',
    databaseURL: 'https://g-austro-default-rtdb.firebaseio.com',
    storageBucket: 'g-austro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxmmqTt0q5vk5Ml87YSMPVHR-KMmMER0',
    appId: '1:257411804002:ios:1f9657c2d43a8daac39a3b',
    messagingSenderId: '257411804002',
    projectId: 'g-austro',
    databaseURL: 'https://g-austro-default-rtdb.firebaseio.com',
    storageBucket: 'g-austro.firebasestorage.app',
    androidClientId: '257411804002-2hcr3a411m672h8umr29771r0t8b13qq.apps.googleusercontent.com',
    iosClientId: '257411804002-jvs7j8dlf0ismtkqekfsi61jtvbd8i5a.apps.googleusercontent.com',
    iosBundleId: 'com.gsc.qb.austro.astrologer',
  );
}
